name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-lint:
    runs-on: ubuntu-latest 
    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python3 -m venv venv  # Matches your local setup
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Lint code with flake8
      - name: Lint code
        run: |
          source venv/bin/activate
          pip install flake8
          flake8 .

      # Step 5: Run tests with pytest
      - name: Run tests
        run: |
          source venv/bin/activate
          pip install pytest
          pytest

  eda:
    runs-on: ubuntu-latest

    needs: test-and-lint 

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      # Step 4: Run EDA script
      - name: Run EDA script
        run: |
          source venv/bin/activate
          python generate_eda.py

      # Step 5: Upload EDA artifacts
      - name: Upload EDA artifacts
        uses: actions/upload-artifact@v3
        with:
          name: eda-output
          path: ./artifacts/
