name: Setup Environment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-setup:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.3

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || echo "No requirements.txt found, skipping dependencies installation."

      # Step 4: Validate Environment
      - name: Verify Python Installation
        run: python --version

      # Step 5: Validate Installed Libraries
      - name: Verify Installed Libraries
        run: pip list
